FROM golang:1.18 as build
ENV GO111MODULE=on
WORKDIR /app
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY . .
WORKDIR /app/onprem-demo/source_images
RUN CGO_ENABLED=0 go build -o onprem-demo-source_images

FROM alpine:latest as server
WORKDIR /app
COPY --from=build /app/onprem-demo/source_images/onprem-demo-source_images /app/onprem-demo-source_images
RUN chmod a+x /app/onprem-demo-source_images
ENTRYPOINT [ "/app/onprem-demo-source_images" ]