FROM golang:1.18 as build
ENV GO111MODULE=on
WORKDIR /app
COPY ./go.mod .
COPY ./go.sum .
RUN go mod download
COPY . .
WORKDIR /app/onprem-demo/sink_inference_server
RUN CGO_ENABLED=0 go build -o onprem-demo-sink_inference_server

FROM alpine:latest as server
WORKDIR /app
COPY --from=build /app/onprem-demo/sink_inference_server/onprem-demo-sink_inference_server /app/onprem-demo-sink_inference_server
RUN chmod a+x /app/onprem-demo-sink_inference_server
ENTRYPOINT [ "/app/onprem-demo-sink_inference_server" ]