# coding: utf-8

"""
    Bacalhau API

    This page is the reference of the Bacalhau REST API. Project docs are available at https://docs.bacalhau.org/. Find more information about Bacalhau at https://github.com/filecoin-project/bacalhau.  # noqa: E501

    OpenAPI spec version: 0.3.22.post4
    Contact: team@bacalhau.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from bacalhau_apiclient.configuration import Configuration


class JobHistory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'compute_reference': 'str',
        'job_id': 'str',
        'new_state': 'str',
        'new_state_type': 'JobHistoryNewStateType',
        'new_version': 'int',
        'node_id': 'str',
        'previous_state': 'str',
        'shard_index': 'int',
        'time': 'str',
        'type': 'JobHistoryType'
    }

    attribute_map = {
        'comment': 'Comment',
        'compute_reference': 'ComputeReference',
        'job_id': 'JobID',
        'new_state': 'NewState',
        'new_state_type': 'NewStateType',
        'new_version': 'NewVersion',
        'node_id': 'NodeID',
        'previous_state': 'PreviousState',
        'shard_index': 'ShardIndex',
        'time': 'Time',
        'type': 'Type'
    }

    def __init__(self, comment=None, compute_reference=None, job_id=None, new_state=None, new_state_type=None, new_version=None, node_id=None, previous_state=None, shard_index=None, time=None, type=None, _configuration=None):  # noqa: E501
        """JobHistory - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._comment = None
        self._compute_reference = None
        self._job_id = None
        self._new_state = None
        self._new_state_type = None
        self._new_version = None
        self._node_id = None
        self._previous_state = None
        self._shard_index = None
        self._time = None
        self._type = None
        self.discriminator = None

        if comment is not None:
            self.comment = comment
        if compute_reference is not None:
            self.compute_reference = compute_reference
        if job_id is not None:
            self.job_id = job_id
        if new_state is not None:
            self.new_state = new_state
        if new_state_type is not None:
            self.new_state_type = new_state_type
        if new_version is not None:
            self.new_version = new_version
        if node_id is not None:
            self.node_id = node_id
        if previous_state is not None:
            self.previous_state = previous_state
        if shard_index is not None:
            self.shard_index = shard_index
        if time is not None:
            self.time = time
        if type is not None:
            self.type = type

    @property
    def comment(self):
        """Gets the comment of this JobHistory.  # noqa: E501


        :return: The comment of this JobHistory.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this JobHistory.


        :param comment: The comment of this JobHistory.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def compute_reference(self):
        """Gets the compute_reference of this JobHistory.  # noqa: E501


        :return: The compute_reference of this JobHistory.  # noqa: E501
        :rtype: str
        """
        return self._compute_reference

    @compute_reference.setter
    def compute_reference(self, compute_reference):
        """Sets the compute_reference of this JobHistory.


        :param compute_reference: The compute_reference of this JobHistory.  # noqa: E501
        :type: str
        """

        self._compute_reference = compute_reference

    @property
    def job_id(self):
        """Gets the job_id of this JobHistory.  # noqa: E501


        :return: The job_id of this JobHistory.  # noqa: E501
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this JobHistory.


        :param job_id: The job_id of this JobHistory.  # noqa: E501
        :type: str
        """

        self._job_id = job_id

    @property
    def new_state(self):
        """Gets the new_state of this JobHistory.  # noqa: E501


        :return: The new_state of this JobHistory.  # noqa: E501
        :rtype: str
        """
        return self._new_state

    @new_state.setter
    def new_state(self, new_state):
        """Sets the new_state of this JobHistory.


        :param new_state: The new_state of this JobHistory.  # noqa: E501
        :type: str
        """

        self._new_state = new_state

    @property
    def new_state_type(self):
        """Gets the new_state_type of this JobHistory.  # noqa: E501


        :return: The new_state_type of this JobHistory.  # noqa: E501
        :rtype: JobHistoryNewStateType
        """
        return self._new_state_type

    @new_state_type.setter
    def new_state_type(self, new_state_type):
        """Sets the new_state_type of this JobHistory.


        :param new_state_type: The new_state_type of this JobHistory.  # noqa: E501
        :type: JobHistoryNewStateType
        """

        self._new_state_type = new_state_type

    @property
    def new_version(self):
        """Gets the new_version of this JobHistory.  # noqa: E501


        :return: The new_version of this JobHistory.  # noqa: E501
        :rtype: int
        """
        return self._new_version

    @new_version.setter
    def new_version(self, new_version):
        """Sets the new_version of this JobHistory.


        :param new_version: The new_version of this JobHistory.  # noqa: E501
        :type: int
        """

        self._new_version = new_version

    @property
    def node_id(self):
        """Gets the node_id of this JobHistory.  # noqa: E501


        :return: The node_id of this JobHistory.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this JobHistory.


        :param node_id: The node_id of this JobHistory.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def previous_state(self):
        """Gets the previous_state of this JobHistory.  # noqa: E501


        :return: The previous_state of this JobHistory.  # noqa: E501
        :rtype: str
        """
        return self._previous_state

    @previous_state.setter
    def previous_state(self, previous_state):
        """Sets the previous_state of this JobHistory.


        :param previous_state: The previous_state of this JobHistory.  # noqa: E501
        :type: str
        """

        self._previous_state = previous_state

    @property
    def shard_index(self):
        """Gets the shard_index of this JobHistory.  # noqa: E501


        :return: The shard_index of this JobHistory.  # noqa: E501
        :rtype: int
        """
        return self._shard_index

    @shard_index.setter
    def shard_index(self, shard_index):
        """Sets the shard_index of this JobHistory.


        :param shard_index: The shard_index of this JobHistory.  # noqa: E501
        :type: int
        """

        self._shard_index = shard_index

    @property
    def time(self):
        """Gets the time of this JobHistory.  # noqa: E501


        :return: The time of this JobHistory.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this JobHistory.


        :param time: The time of this JobHistory.  # noqa: E501
        :type: str
        """

        self._time = time

    @property
    def type(self):
        """Gets the type of this JobHistory.  # noqa: E501


        :return: The type of this JobHistory.  # noqa: E501
        :rtype: JobHistoryType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this JobHistory.


        :param type: The type of this JobHistory.  # noqa: E501
        :type: JobHistoryType
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobHistory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobHistory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JobHistory):
            return True

        return self.to_dict() != other.to_dict()
