// Code generated by "stringer -type=WSControlEventType --trimprefix=WSControlEvent"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[wsControlEventUnknown-0]
	_ = x[WSControlEventSubscribe-1]
	_ = x[WSControlEventUnsubscribe-2]
	_ = x[wsControlEventDone-3]
}

const _WSControlEventType_name = "wsControlEventUnknownSubscribeUnsubscribewsControlEventDone"

var _WSControlEventType_index = [...]uint8{0, 21, 30, 41, 59}

func (i WSControlEventType) String() string {
	if i < 0 || i >= WSControlEventType(len(_WSControlEventType_index)-1) {
		return "WSControlEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WSControlEventType_name[_WSControlEventType_index[i]:_WSControlEventType_index[i+1]]
}
